// SPDX-FileCopyrightText: 2026 AdobeWan
// SPDX-License-Identifier: MIT
//
// Bundle the tested core physics and the Gladius profile for the alpha page (site/vendor/speedwall-core.mjs).
// The profile is built and Zod-validated here in Node, then inlined as plain data.   pnpm build:alpha
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fixtureSchema } from "../packages/data-gladius/dist/fixture-schema.js";
import { profileFromFixture } from "../packages/data-gladius/dist/index.js";
import { flightProfileSchema } from "../packages/core/dist/schema.js";

const out = "site/vendor/speedwall-core.mjs";
const profile = flightProfileSchema.parse(profileFromFixture(fixtureSchema.parse(JSON.parse(readFileSync("research/gladius-v1-fixture.json", "utf8")))));
delete profile.provenance; // documented in the repo; not needed by the page
const r = await build({
  stdin: {
    contents: `export { step, derive, restState, capped, boostActive, eggRadius, eggRadiusAlong, lateralRoom, DT, G0 } from "./packages/core/src/index.ts";
export const gladius = ${JSON.stringify(profile)};`,
    resolveDir: ".", loader: "ts",
  },
  bundle: true, format: "esm", minify: true, write: false, target: "es2020",
});
const banner = "// Speedwall Lab core physics + Gladius profile. Generated by tools/build-alpha.mjs from packages/core and\n// research/gladius-v1-fixture.json; do not edit. Code MIT; Gladius data CC BY 4.0 (AdobeWan), except the values NOTICE.md lists.\n";
writeFileSync(out, banner + r.outputFiles[0].text);
console.log(`${out}: ${(r.outputFiles[0].text.length / 1024).toFixed(1)} KB`);
